---
name: "CHECKOUT"
description: "git clone and checkout"
author: "shoce"
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        GITHUB_SERVER="${{ github.server_url }}"
        GITHUB_SERVER="${GITHUB_SERVER#https://}"
        echo "GITHUB_SERVER=$GITHUB_SERVER" >> $GITHUB_ENV
        #
        echo "server ${GITHUB_SERVER}"
        echo "repo ${{ github.repository }}"
        echo "sha ${{ github.sha }}"
        echo "token ${{ github.token }}"
        #
        git config --global advice.detachedHead false
        git clone --no-checkout https://x-access-token:${{ github.token }}@${GITHUB_SERVER}/${{ github.repository }}.git .
        git fetch --depth=1 origin ${{ github.sha }}
        git checkout FETCH_HEAD


